spring.application.name=workhub
server.port=8082
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/db_workhub
spring.datasource.username=user_fevi
spring.datasource.password=123456